#!/usr/bin/env python3
"""Generate Splat function symbols from the checked-in Ghidra CSV export."""

from __future__ import annotations

import argparse
import csv
import re
from dataclasses import dataclass
from pathlib import Path


RAM_START = 0x80010000
RAM_END = 0x800AF800
VALID_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")


@dataclass(frozen=True, order=True)
class Function:
    address: int
    size: int
    name: str


def load_functions(path: Path) -> list[Function]:
    functions: list[Function] = []
    with path.open(newline="", encoding="utf-8") as source:
        for row in csv.DictReader(source):
            address = int(row["address"], 16)
            if not RAM_START <= address < RAM_END:
                continue
            function = Function(address, int(row["size"]), row["name"])
            if function.size <= 0 or function.address % 4 or function.size % 4:
                raise ValueError(f"unaligned function: {function}")
            if not VALID_NAME.fullmatch(function.name):
                raise ValueError(f"invalid symbol name: {function.name!r}")
            functions.append(function)

    functions.sort()
    names: set[str] = set()
    previous_end = RAM_START
    for function in functions:
        if function.name in names:
            raise ValueError(f"duplicate symbol: {function.name}")
        if function.address < previous_end:
            raise ValueError(f"overlapping function at 0x{function.address:08X}")
        if function.address + function.size > RAM_END:
            raise ValueError(f"function outside executable: {function}")
        names.add(function.name)
        previous_end = function.address + function.size
    return functions


def render(functions: list[Function]) -> str:
    lines = [
        "// Generated by scripts/generate_splat_symbols.py from ghidra_out/functions.csv.",
        "// Only symbols inside the PS-X EXE load range are imported.",
        "",
    ]
    for function in functions:
        lines.append(
            f"{function.name} = 0x{function.address:08X}; "
            f"// type:func size:0x{function.size:X} segment:main"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=Path("ghidra_out/functions.csv"))
    parser.add_argument("--output", type=Path, default=Path("config/symbol_addrs.txt"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    functions = load_functions(args.input)
    generated = render(functions)
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"outdated generated file: {args.output}")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(generated, encoding="utf-8", newline="\n")
    print(f"PASS — {len(functions)} function symbols in {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
